@extends('partials.layout')

@section('content')

<!-- BEGIN: CONTENT/FEATURES/FEATURES-1 -->
<div class="c-content-box c-size-md c-bg-white">
    <div class="container">
        <div class="row">
        	<div class="section-context">
            	<p>
            	La <a href="http://bd.eionet.europa.eu/activities/Reporting/Article_17">Direttiva Habitat (92/43/CEE)</a>, insieme alla <a href="http://bd.eionet.europa.eu/activities/Reporting/Article_12">Direttiva Uccelli (2009/147/CE)</a>, rappresenta il principale pilastro della politica comunitaria per la conservazione della natura e comporta l’obbligo per gli Stati Membri di redigere, ogni 6 anni, un Rapporto nazionale sullo stato di conservazione delle specie e degli habitat di interesse comunitario e sulle misure di conservazione intraprese, secondo quanto previsto dall’articolo 17.</p>
				<p>Con il recepimento della Direttiva da parte dell’Italia tramite il <a href="http://www.minambiente.it/sites/default/files/archivio/allegati/rete_natura_2000/Regolamento_D.P.R._8_settembre_1997_n._357.PDF">Regolamento D.P.R. 8 settembre 1997 n.357</a>, il Ministero dell’Ambiente e della Tutela del Territorio e del Mare ha l’obbligo di redigere il <a href="http://cdr.eionet.europa.eu/it/eu/art17/envupyjhw">Rapporto nazionale</a> periodico a partire dai risultati del monitoraggio che le Regioni e le Province Autonome sono tenute a trasmettere secondo quanto previsto dall’articolo 13, comma 2, dello stesso Decreto.</p>
				<p>La Direttiva Habitat impone la realizzazione di attività di sorveglianza, l’attivazione di misure di conservazione e la valutazione della loro efficacia.  Monitoraggio e reporting devono essere effettuati sia all’interno sia all’esterno della Rete Natura 2000, per verificare l’efficacia dell’applicazione della direttiva nello Stato membro nel suo complesso. I principali risultati del monitoraggio devono essere presentati alla CE ogni sei anni, insieme alle informazioni riguardanti lo stato di attuazione della direttiva stessa. Il monitoraggio, oltre ad ottemperare agli obblighi ex Art. 17, ha lo scopo di verificare anche l’efficacia delle misure di conservazione e dei piani di gestione previsti per le Zone Speciali di Conservazione (ZSC), in coerenza con i relativi obiettivi. Sulla base dei rapporti nazionali la CE effettua le valutazioni complessive dello stato di conservazione a livello di regione biogeografica di ciascuna specie e habitat e produce sintesi dei risultati a livello <a href="http://bd.eionet.europa.eu/activities/Reporting/Article_17/Reports_2013" target="_blank">europeo</a>.</p>
				<p>Dall’entrata in vigore della Direttiva sono già stati prodotti dagli Stati Membri tre <a href="http://ec.europa.eu/environment/nature/knowledge/rep_habitats/index_en.htm" target="_blank">National Report</a>, di cui gli ultimi due (2° Report relativo al periodo 2001-2006; 3° Report relativo al periodo 2007-2012) contengono le valutazioni dello stato di conservazione di specie e habitat.</p>
				<p>In Italia il 3° Rapporto Nazionale (inviato alla CE nel dicembre 2013) è stato prodotto grazie ad un programma di lavoro coordinato dal Ministero dell’Ambiente e della Tutela del Territorio e del Mare e realizzato da ISPRA con il contributo delle Regioni e Province Autonome e delle principali Società Scientifiche nazionali, realizzando un avanzamento verso l’adeguamento agli standard richiesti dal sistema di <em>reporting</em>. Il rapporto ha mostrato un generale miglioramento nello stato delle conoscenze per specie e habitat di interesse comunitario ma ha anche evidenziato che permangono carenze conoscitive in diverse aree del Paese, eterogeneità dei dati e mancanza di programmi di monitoraggio  finalizzati a rispondere adeguatamente alle richieste della Commissione Europea.</p>
				<p>In considerazione di quanto emerso nel III Rapporto Nazionale, ed in vista del prossimo reporting, è stato avviato un progetto nazionale per fornire strumenti utili a colmare le carenze riscontrate nel contesto italiano. La finalità principale di tale progetto è stata quella di definire e diffondere metodiche di monitoraggio per specie e habitat italiani di interesse comunitario, coerenti con le richieste del sistema europeo, basate sulle migliori conoscenze scientifiche e condivise tra tutti gli enti coinvolti. Con questo obiettivo ISPRA, su incarico del Ministero dell’Ambiente e della Tutela del Territorio e del Mare e in condivisione con Regioni e Province Autonome, ha avviato nel 2015 una collaborazione con le principali Società scientifiche nazionali per la definizione delle metodiche di monitoraggio per fauna, flora e habitat terrestri e di acqua dolce di interesse comunitario. Nel progetto non sono stati trattati specie ed habitat marini.</p>
				<p>In tale contesto sono stati prodotti i tre manuali per il Monitoraggio delle specie animali, vegetali e degli habitat di interesse comunitario in Italia (scaricabili da questo sito nella sezione download). I manuali hanno lo scopo di fornire gli strumenti metodologici utili per assicurare una standardizzazione dei metodi di raccolta dati, da parte dei soggetti incaricati, necessari alla redazione del 4° Rapporto nazionale italiano, che andrà inviato alla Commissione nel 2019.</p>
				<p>Complessivamente, tra specie ed habitat, sono state prodotte 393 schede (scaricabili da questo sito nella sezione download); ogni scheda è stata sviluppata dagli esperti di ISPRA in contatto con il Ministero dell’Ambiente e con il supporto delle sette principali società scientifiche nazionali di ambito faunistico, floristico e vegetazionale. Tutte le schede sono state, inoltre, riviste ed integrate dai tecnici delle Regioni e Province Autonome, che sono gli enti responsabili del monitoraggio ai sensi della Direttiva Habitat in Italia. Il progetto, in tutte le sue fasi di realizzazione, ha permesso la partecipazione dei maggiori esperti dei diversi gruppi tassonomici e di habitat.  I manuali prodotti e le schede in essi contenute, riportano le metodologie specie-specifiche/habitat-specifiche da applicare nei monitoraggi, al fine di migliorare la coerenza dei dati raccolti sul campo con quanto richiesto dal sistema europeo di reporting e di ottimizzare le attività di monitoraggio a livello nazionale.</p>
				<p>&nbsp;</p>
				<p><strong>SCHEDE DI MONITORAGGIO</strong></p>
				<p><strong>SPECIE ANIMALI: </strong><strong>151 schede</strong> descrivono tecniche e protocolli di monitoraggio per le 215 specie animali di interesse comunitario presenti in Italia (62 invertebrati, 30 pesci d’acqua dolce, 71 anfibi e rettili e 52 mammiferi).</p>
				<p><strong>SPECIE VEGETALI: </strong><strong>118 schede</strong> descrivono tecniche e protocolli di monitoraggio per i 118 taxa vegetali italiani di interesse comunitario presenti in Italia (107 piante vascolari, 10 briofite, 1 taxon lichenico).</p>
				<p><strong>HABITAT: </strong><strong>124 schede</strong> descrivono tecniche e protocolli di monitoraggio per i tipi di habitat naturali di interesse comunitario presenti in Italia (21 Habitat costieri e dune, 15 Habitat d’acqua dolce, 16 Arbusteti e macchie, 15 Formazioni erbose, 8 Torbiere e paludi, 10 Habitat rocciosi, 39 Habitat forestali).
				</p>
            </div>  
        </div> 
    </div>
</div>
<!-- END: CONTENT/FEATURES/FEATURES-1 -->

@endsection